### PR TITLE
Typo: Missing an article

### PR DESCRIPTION
**Pull request by mbbroberg**
Minor edit for readability.

### CODE REVIEW

**Comment by mbbroberg** [comment]
@stefanoverna huh, it's strange to me that you don't want to merge a fix to a grammatical error into your website when your documentation asks to open a PR if users see typos. 🤷‍♂️

**Comment by stefanoverna** [comment]
Whoops, actually I clicked the wrong button xD will be merged, thanks so much for your help!! :)

**Comment by mbbroberg** [comment]
Ha! It happens - no worries :)

**Comment by mbbroberg** [comment]
☝️ I added the branch back

**Pull request closed without merging**
